spring.application.name=proyecto-software

########## CONEXION BASE DE DATOS #########
spring.datasource.url=jdbc:postgresql://dpg-d8hd4nt7vvec73drt5e0-a.oregon-postgres.render.com:5432/tickethub_db_s6gv?sslmode=require
spring.datasource.username=tickethub_user
spring.datasource.password=tbvcX8XjrLlGEiCdDRZUTacnIPeziTHe
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT:8080}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=5

########## JWT #########
jwt.secret=${JWT_SECRET:miClaveSuperSegura1234567890abcdefghijklmn}
app.jwt.secret=${JWT_SECRET:miClaveSuperSegura1234567890abcdefghijklmn}
app.jwt.issuer=SIT-System
app.jwt.access-expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000
app.jwt.verify-email-expiration-ms=86400000
app.jwt.reset-password-expiration-ms=3600000

########## BREVO #########
brevo.api-key=${BREVO_API_KEY:dummy_key}
brevo.api-url=${BREVO_API_URL:https://api.brevo.com/v3}
brevo.sender.email=${BREVO_SENDER_EMAIL:no-reply@test.com}
brevo.sender.name=${BREVO_SENDER_NAME:SIT_System}

########## FRONTEND #########
app.frontend.url=${FRONTEND_URL:http://localhost:5173}

########## SEGURIDAD #########
app.security.max-intentos-fallidos=${MAX_INTENTOS_FALLIDOS:5}
app.security.bloqueo-minutos=${BLOQUEO_MINUTOS:30}

########## CORS #########
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,https://tickethub-full.vercel.app}

########## LOGGING #########
logging.level.com.sit=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG